# @package _global_

defaults:
  - override /data: fold100
  - override /model: fasterwam
  - _self_

training_scope: action_adapter
init_checkpoint: /media/sata4t/hy_fasterwam_checkpoints/fasterwam_release/robotwin/step_029355.pt
action_delta_checkpoint: null
save_optimizer_state: true

batch_size: 1
num_workers: 4
lr_scheduler_type: cosine
learning_rate: 1.0e-4
num_epochs: 1
max_steps: 800
log_every: 10
save_every: 200
eval_every: 0
gradient_accumulation_steps: 8
weight_decay: 1.0e-2
resume: null

model:
  skip_dit_load_from_pretrain: true
  action_dit_pretrained_path: null
  mot_checkpoint_mixed_attn: false
  loss:
    lambda_video: 0.0
    lambda_action: 1.0

wandb:
  enabled: false
  name: fold100_fasterwam_action_adapter
